services:
  HRDirectorService:
    image: hrdirector
    networks:
      - app-network
    build:
      context: .
      dockerfile: hrdirector/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
    ports:
      - "9090:8080"
    environment:
      RABBITMQ_HOST_NAME: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASSWORD: password
      DATABASE_URI: "Server=db;Port=5432;Database=hackathon;User Id=postgres;Password=postgres;"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:80 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
  
  HRManagerService:
    image: hrmanager
    networks:
      - app-network
    build:
      context: .
      dockerfile: hrmanager/Dockerfile
    depends_on:
      HRDirectorService:
        condition: service_healthy
      Junior1:
        condition: service_healthy
      Junior2:
        condition: service_healthy
      Junior3:
        condition: service_healthy
      Junior4:
        condition: service_healthy
      Junior5:
        condition: service_healthy
      TeamLead1:
        condition: service_healthy
      TeamLead2:
        condition: service_healthy
      TeamLead3:
        condition: service_healthy
      TeamLead4:
        condition: service_healthy
      TeamLead5:
        condition: service_healthy
    environment:
      RABBITMQ_HOST_NAME: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASSWORD: password
      DIRECTOR_URI: hrdirector:8080
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:80 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  Junior1:
    image: member
    networks:
      - app-network
    build:
      context: .
      dockerfile: member/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      ID: 1
      TYPE: junior
      RABBITMQ_HOST_NAME: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:80 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
  
  Junior2:
    image: member
    networks:
      - app-network
    build:
      context: .
      dockerfile: member/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      ID: 2
      TYPE: junior
      RABBITMQ_HOST_NAME: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:80 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  Junior3:
    image: member
    networks:
      - app-network
    build:
      context: .
      dockerfile: member/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      ID: 3
      TYPE: junior
      RABBITMQ_HOST_NAME: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:80 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
  
  Junior4:
    image: member
    networks:
      - app-network
    build:
      context: .
      dockerfile: member/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      ID: 4
      TYPE: junior
      RABBITMQ_HOST_NAME: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:80 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
  
  Junior5:
    image: member
    networks:
      - app-network
    build:
      context: .
      dockerfile: member/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      ID: 5
      TYPE: junior
      RABBITMQ_HOST_NAME: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:80 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
  
  TeamLead1:
    image: member
    networks:
      - app-network
    depends_on:
      rabbitmq:
        condition: service_healthy
    build:
      context: .
      dockerfile: member/Dockerfile
    environment:
      ID: 1
      TYPE: teamlead
      RABBITMQ_HOST_NAME: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:80 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
  
  TeamLead2:
    image: member
    networks:
      - app-network
    depends_on:
      rabbitmq:
        condition: service_healthy
    build:
      context: .
      dockerfile: member/Dockerfile
    environment:
      ID: 2
      TYPE: teamlead
      RABBITMQ_HOST_NAME: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:80 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
  
  TeamLead3:
    image: member
    networks:
      - app-network
    depends_on:
      rabbitmq:
        condition: service_healthy
    build:
      context: .
      dockerfile: member/Dockerfile
    environment:
      ID: 3
      TYPE: teamlead
      RABBITMQ_HOST_NAME: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:80 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
  
  TeamLead4:
    image: member
    networks:
      - app-network
    depends_on:
      rabbitmq:
        condition: service_healthy
    build:
      context: .
      dockerfile: member/Dockerfile
    environment:
      ID: 4
      TYPE: teamlead
      RABBITMQ_HOST_NAME: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:80 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
  
  TeamLead5:
    image: member
    networks:
      - app-network
    depends_on:
      rabbitmq:
        condition: service_healthy
    build:
      context: .
      dockerfile: member/Dockerfile
    environment:
      ID: 5
      TYPE: teamlead
      RABBITMQ_HOST_NAME: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:80 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
  
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network
    environment:
      RABBITMQ_LOGS: "true"
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 5s
      timeout: 0s
      retries: 5

  db:
    image: postgres:15
    networks:
      - app-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hackathon
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  rabbitmq_data:
    driver: local
  rabbitmq_logs:
    driver: local

networks:
  app-network:
    driver: bridge