services:
  rabbitmq:
    image: "rabbitmq:3.11-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - hackathon_network
    environment:
      RABBITMQ_LOGS: "true"
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 10s
      retries: 10

  db:
    image: postgres:15
    networks:
      - hackathon_network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hackathon
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  HRDirectorService:
    image: hrdirector
    networks:
      - hackathon_network
    build:
      context: .
      dockerfile: hrdirector/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "8085:8085"
    environment:
      RABBITMQ_HOST_NAME: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASSWORD: password
      DATABASE_URI: "Server=db;Port=5432;Database=hackathon;User Id=postgres;Password=postgres;"
        #    healthcheck:
        #      test: [ "CMD-SHELL", "curl -f http://localhost:80/health || exit 1" ]
        #      interval: 30s
        #      timeout: 10s
        #      retries: 3
  
  
  HRManagerService:
    image: hrmanager
    networks:
      - hackathon_network
    build:
      context: .
      dockerfile: hrmanager/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
      HRDirectorService:
        condition: service_started
    environment:
      RABBITMQ_HOST_NAME: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASSWORD: password
      DIRECTOR_URI: HRDirectorService:8080
    entrypoint: [ "sh", "-c", "sleep 30 && dotnet hrmanager.dll" ]

  Junior1:
    image: member
    networks:
      - hackathon_network
    build:
      context: .
      dockerfile: member/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:
      ID: 1
      TYPE: junior
      RABBITMQ_HOST_NAME: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASSWORD: password
  
  Junior2:
    image: member
    networks:
      - hackathon_network
    build:
      context: .
      dockerfile: member/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:
      ID: 2
      TYPE: junior
      RABBITMQ_HOST_NAME: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASSWORD: password

  Junior3:
    image: member
    networks:
      - hackathon_network
    build:
      context: .
      dockerfile: member/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:
      ID: 3
      TYPE: junior
      RABBITMQ_HOST_NAME: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASSWORD: password
  
  Junior4:
    image: member
    networks:
      - hackathon_network
    build:
      context: .
      dockerfile: member/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:
      ID: 4
      TYPE: junior
      RABBITMQ_HOST_NAME: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASSWORD: password
  
  Junior5:
    image: member
    networks:
      - hackathon_network
    build:
      context: .
      dockerfile: member/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:
      ID: 5
      TYPE: junior
      RABBITMQ_HOST_NAME: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASSWORD: password
  
  TeamLead1:
    image: member
    networks:
      - hackathon_network
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: member/Dockerfile
    environment:
      ID: 1
      TYPE: teamlead
      RABBITMQ_HOST_NAME: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASSWORD: password
  
  TeamLead2:
    image: member
    networks:
      - hackathon_network
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: member/Dockerfile
    environment:
      ID: 2
      TYPE: teamlead
      RABBITMQ_HOST_NAME: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASSWORD: password
  
  TeamLead3:
    image: member
    networks:
      - hackathon_network
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: member/Dockerfile
    environment:
      ID: 3
      TYPE: teamlead
      RABBITMQ_HOST_NAME: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASSWORD: password
  
  TeamLead4:
    image: member
    networks:
      - hackathon_network
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: member/Dockerfile
    environment:
      ID: 4
      TYPE: teamlead
      RABBITMQ_HOST_NAME: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASSWORD: password
  
  TeamLead5:
    image: member
    networks:
      - hackathon_network
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: member/Dockerfile
    environment:
      ID: 5
      TYPE: teamlead
      RABBITMQ_HOST_NAME: rabbitmq
      RABBITMQ_USER: user
      RABBITMQ_PASSWORD: password

volumes:
  rabbitmq_data:
    driver: local
  rabbitmq_logs:
    driver: local

networks:
  hackathon_network:
    driver: bridge